### ISSUE TITLE
Manual Please.

### ISSUE THREAD

**Issue by McGroggin** [VegaDeftwing/PinkTromboneVCV#6]
...

**Comment by VegaDeftwing** [comment]
The reason there isn't one is because, well, it's the pink trombone. It's literally a port of https://dood.al/pinktrombone/ so if it works there, it works in VCV - and like the original, it's about exploring the sounds and making silly noises. A manual would, imho, take away from the fun.

**Comment by McGroggin** [comment]
Now that I've played with it a bit a manual isn't really a necessity.

I was being a bit salty there and I apologize for that.

I'm generally frustrated that so many modules (and open source projects in general) do not come with manuals and am not really a fan of the whole 'manuals take the fun away' line of reasoning. At a minimum I think every modules should at least come with CV input range specifications (or at least in the new tool-tips feature).

The module looks and sounds great. It even had me giggling a few times.

Cheers!
